In [1]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np 
import os
import pandas as pd

In [2]:
df1 = pd.read_csv('../archive/IPL_Ball_by_Ball_2008_2022.csv')
df1.dataframeName = 'deliveries.csv'

In [3]:
df1.head(5)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [4]:
len(df1)

225954

In [24]:
player_subset = df1[df1["batter"] == 'SN Khan']
player_subset

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
1231,1304115,1,5,5,SN Khan,JJ Bumrah,RR Pant,NaN,0,0,0,0,0,NaN,NaN,NaN,Delhi Capitals
1232,1304115,1,5,6,SN Khan,JJ Bumrah,RR Pant,NaN,6,0,6,0,0,NaN,NaN,NaN,Delhi Capitals
1236,1304115,1,6,4,SN Khan,M Markande,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
1239,1304115,1,7,1,SN Khan,RP Meredith,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
1241,1304115,1,7,3,SN Khan,RP Meredith,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112202,829745,2,12,1,SN Khan,IC Pandey,V Kohli,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112205,829745,2,12,4,SN Khan,IC Pandey,V Kohli,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112208,829745,2,13,1,SN Khan,RA Jadeja,V Kohli,NaN,6,0,6,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112209,829745,2,13,2,SN Khan,RA Jadeja,V Kohli,NaN,2,0,2,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112210,829745,2,13,3,SN Khan,RA Jadeja,V Kohli,NaN,0,0,0,0,1,SN Khan,caught,MM Sharma,Royal Challengers Bangalore

In [25]:
df2 = pd.read_csv('../archive/IPL_Matches_2008_2022.csv')
df2.dataframeName = 'matches.csv'

In [26]:
df2.head(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,29-05-2022,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,27-05-2022,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,25-05-2022,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,24-05-2022,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,22-05-2022,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [27]:
venue_subset = df2[df2["City"] == 'Centurion']
venue_subset

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
837,392237,Centurion,22-05-2009,2009,Semi Final,Delhi Daredevils,Deccan Chargers,SuperSport Park,Deccan Chargers,field,N,Deccan Chargers,Wickets,6.0,NaN,AC Gilchrist,"['G Gambhir', 'DA Warner', 'V Sehwag', 'TM Dil...","['AC Gilchrist', 'HH Gibbs', 'AA Bilakhia', 'T...",BR Doctrove,DJ Harper
838,392236,Centurion,21-05-2009,2009,56,Royal Challengers Bangalore,Deccan Chargers,SuperSport Park,Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,12.0,NaN,MK Pandey,"['JH Kallis', 'MK Pandey', 'RE van der Merwe',...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'A Sy...",IL Howell,S Ravi
839,392235,Centurion,21-05-2009,2009,55,Delhi Daredevils,Mumbai Indians,SuperSport Park,Delhi Daredevils,field,N,Delhi Daredevils,Wickets,4.0,NaN,V Sehwag,"['G Gambhir', 'DA Warner', 'V Sehwag', 'TM Dil...","['ST Jayasuriya', 'SR Tendulkar', 'JP Duminy',...",IL Howell,S Ravi
843,392231,Centurion,18-05-2009,2009,51,Chennai Super Kings,Kolkata Knight Riders,SuperSport Park,Chennai Super Kings,bat,N,Kolkata Knight Riders,Wickets,7.0,NaN,BJ Hodge,"['PA Patel', 'GJ Bailey', 'SK Raina', 'MS Dhon...","['BB McCullum', 'SC Ganguly', 'BJ Hodge', 'DJ ...",SJA Taufel,RB Tiffin
852,392222,Centurion,12-05-2009,2009,42,Kings XI Punjab,Mumbai Indians,SuperSport Park,Kings XI Punjab,bat,N,Mumbai Indians,Wickets,8.0,NaN,Harbhajan Singh,"['S Sohal', 'SM Katich', 'IK Pathan', 'KC Sang...","['ST Jayasuriya', 'DJ Bravo', 'AM Rahane', 'SR...",SS Hazare,RE Koertzen
853,392221,Centurion,12-05-2009,2009,41,Royal Challengers Bangalore,Kolkata Knight Riders,SuperSport Park,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,6.0,NaN,LRPL Taylor,"['JD Ryder', 'JH Kallis', 'RV Uthappa', 'LRPL ...","['BB McCullum', 'SC Ganguly', 'AN Ghosh', 'DJ ...",M Erasmus,SS Hazare
860,392214,Centurion,07-05-2009,2009,34,Chennai Super Kings,Kings XI Punjab,SuperSport Park,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,12.0,D/L,ML Hayden,"['S Badrinath', 'ML Hayden', 'SK Raina', 'MS D...","['S Sohal', 'SM Katich', 'K Goel', 'Yuvraj Sin...",DJ Harper,TH Wijewardene
861,392213,Centurion,07-05-2009,2009,33,Royal Challengers Bangalore,Rajasthan Royals,SuperSport Park,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,A Singh,"['JH Kallis', 'W Jaffer', 'RV Uthappa', 'R Dra...","['GC Smith', 'NV Ojha', 'LA Carseldine', 'YK P...",K Hariharan,DJ Harper
862,392212,Centurion,06-05-2009,2009,32,Deccan Chargers,Mumbai Indians,SuperSport Park,Deccan Chargers,bat,N,Deccan Chargers,Runs,19.0,NaN,RG Sharma,"['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'RG S...","['ST Jayasuriya', 'SR Tendulkar', 'PR Shah', '...",MR Benson,HDPK Dharmasena
872,392202,Centurion,30-04-2009,2009,22,Chennai Super Kings,Rajasthan Royals,SuperSport Park,Rajasthan Royals,field,N,Chennai Super Kings,Runs,38.0,NaN,SK Raina,"['PA Patel', 'ML Hayden', 'SK Raina', 'S Badri...","['RJ Quiney', 'GC Smith', 'SA Asnodkar', 'RA J...",GAV Baxter,RE Koertzen
873,392201,Centurion,30-04-2009,2009,21,Deccan Chargers,Delhi Daredevils,SuperSport Park,Delhi Daredevils,field,N,Delhi Daredevils,Wickets,6.0,NaN,DP Nannes,"['AC Gilchrist', 'HH Gibbs', 'AA Bilakhia', 'R...","['G Gambhir', 'V Sehwag', 'AB de Villiers', 'T...",GAV Baxter,AM Saheba
876,392198,Centurion,28-04-2009,2009,18,Delhi Daredevils,Rajasthan Royals,SuperSport Park,Delhi Daredevils,bat,N,Rajasthan Royals,Wickets,5.0,NaN,YK Pathan,"['G Gambhir', 'V Sehwag', 'AB de Villiers', 'T...","['RJ Quiney', 'GC Smith', 'SA Asnodkar', 'PC V...",GAV Baxter,RE Koertzen

In [28]:
match_id_list = venue_subset["ID"].to_numpy()
print(match_id_list)

[392237 392236 392235 392231 392222 392221 392214 392213 392212 392202
 392201 392198]

In [29]:
m = len(match_id_list)

In [30]:
player_subset

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
1231,1304115,1,5,5,SN Khan,JJ Bumrah,RR Pant,NaN,0,0,0,0,0,NaN,NaN,NaN,Delhi Capitals
1232,1304115,1,5,6,SN Khan,JJ Bumrah,RR Pant,NaN,6,0,6,0,0,NaN,NaN,NaN,Delhi Capitals
1236,1304115,1,6,4,SN Khan,M Markande,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
1239,1304115,1,7,1,SN Khan,RP Meredith,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
1241,1304115,1,7,3,SN Khan,RP Meredith,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112202,829745,2,12,1,SN Khan,IC Pandey,V Kohli,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112205,829745,2,12,4,SN Khan,IC Pandey,V Kohli,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112208,829745,2,13,1,SN Khan,RA Jadeja,V Kohli,NaN,6,0,6,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112209,829745,2,13,2,SN Khan,RA Jadeja,V Kohli,NaN,2,0,2,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112210,829745,2,13,3,SN Khan,RA Jadeja,V Kohli,NaN,0,0,0,0,1,SN Khan,caught,MM Sharma,Royal Challengers Bangalore

In [31]:
final_df = []
for i in range(len(player_subset)):
    if player_subset.iat[i,0] in match_id_list:
        final_df.append(player_subset.iloc[i])

In [32]:
final_df

[]

In [33]:
final_df = pd.DataFrame(final_df)

In [34]:
final_df

Empty DataFrame
Columns: []
Index: []

In [35]:
#Overall
if len(final_df)!=0:
    
    total_runs = final_df["batsman_run"].sum()
    print(total_runs)

    total_innings = len(pd.unique(final_df['ID']))
    print(total_innings)

    total_outs = final_df[final_df["player_out"] == 'DA Warner']
    print(len(total_outs))

    if len(total_outs)==0:
        print("Player not yet dismissed at ground")
    
    else:
        average = total_runs / len(total_outs)
        print(average)

    strike_rate = total_runs / len(final_df) * 100
    print(strike_rate)

    dots = final_df[final_df["batsman_run"] == 0]
    dot_percentage = len(dots)/len(final_df) * 100
    print(dot_percentage)

    boundaries = final_df[final_df["batsman_run"] == 4]
    sixes =  final_df[final_df["batsman_run"] == 6]
    boundary_percentage = len(boundaries) + len(sixes) / len(final_df) * 100
    print(boundary_percentage)

else:
    print("Player not played at ground")

Player not played at ground

In [38]:
#1st_innings
if len(final_df)==0:
    print("Player not played in ground")
    
else:
    final_df_1 = final_df[final_df["inning"]==1]

    if len(final_df_1)!=0:

        total_runs = final_df_1["batsman_run"].sum()
        print(total_runs)

        total_innings = len(pd.unique(final_df_1['ID']))
        print(total_innings)

        total_outs = final_df_1[final_df_1["player_out"] == 'DA Warner']
        print(len(total_outs))

        if len(total_outs)==0:
            print("Player not yet dismissed at ground")

        else:
            average = total_runs / len(total_outs)
            print(average)

        strike_rate = total_runs / len(final_df_1) * 100
        print(strike_rate)

        dots = final_df_1[final_df_1["batsman_run"] == 0]
        dot_percentage = len(dots)/len(final_df_1) * 100
        print(dot_percentage)

        boundaries = final_df_1[final_df_1["batsman_run"] == 4]
        sixes =  final_df_1[final_df_1["batsman_run"] == 6]
        boundary_percentage = len(boundaries) + len(sixes) / len(final_df_1) * 100
        print(boundary_percentage)
    else:
            print("Player not played at ground in 1st innings")

Player not played in ground

In [39]:
#2nd_innings
if len(final_df)==0:
    print("Player not played in ground")
    
else:
    final_df_2 = final_df[final_df["innings"]==2]
    
    if len(final_df_2)!=0:
        total_runs = final_df_2["batsman_run"].sum()
        print(total_runs)

        total_innings = len(pd.unique(final_df_2['ID']))
        print(total_innings)

        total_outs = final_df_2[final_df_2["player_out"] == 'DA Warner']
        print(len(total_outs))

        if len(total_outs)==0:
                print("Player not yet dismissed at ground")

        else:
            average = total_runs / len(total_outs)
            print(average)

        strike_rate = total_runs / len(final_df_2) * 100
        print(strike_rate)

        dots = final_df_2[final_df_2["batsman_run"] == 0]
        dot_percentage = len(dots)/len(final_df_2) * 100
        print(dot_percentage)

        boundaries = final_df_2[final_df_2["batsman_run"] == 4]
        sixes =  final_df_2[final_df_2["batsman_run"] == 6]
        boundary_percentage = len(boundaries) + len(sixes) / len(final_df_2) * 100
        print(boundary_percentage)
        
    else:
            print("Player not played at ground in 2nd innings")

Player not played in ground