In [1]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np 
import os
import pandas as pd

In [2]:
df1 = pd.read_csv('../archive/IPL_Ball_by_Ball_2008_2022.csv')
df1.dataframeName = 'deliveries.csv'

In [3]:
df1.head(5)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [4]:
len(df1)

225954

In [5]:
player_subset = df1[df1["batter"] == 'SN Khan']
player_subset

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
1231,1304115,1,5,5,SN Khan,JJ Bumrah,RR Pant,NaN,0,0,0,0,0,NaN,NaN,NaN,Delhi Capitals
1232,1304115,1,5,6,SN Khan,JJ Bumrah,RR Pant,NaN,6,0,6,0,0,NaN,NaN,NaN,Delhi Capitals
1236,1304115,1,6,4,SN Khan,M Markande,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
1239,1304115,1,7,1,SN Khan,RP Meredith,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
1241,1304115,1,7,3,SN Khan,RP Meredith,RR Pant,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Capitals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112202,829745,2,12,1,SN Khan,IC Pandey,V Kohli,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112205,829745,2,12,4,SN Khan,IC Pandey,V Kohli,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112208,829745,2,13,1,SN Khan,RA Jadeja,V Kohli,NaN,6,0,6,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112209,829745,2,13,2,SN Khan,RA Jadeja,V Kohli,NaN,2,0,2,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
112210,829745,2,13,3,SN Khan,RA Jadeja,V Kohli,NaN,0,0,0,0,1,SN Khan,caught,MM Sharma,Royal Challengers Bangalore

In [6]:
df2 = pd.read_csv('../archive/IPL_Matches_2008_2022.csv')
df2.dataframeName = 'matches.csv'

In [7]:
df2.head(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,29-05-2022,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,27-05-2022,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,25-05-2022,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,24-05-2022,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,22-05-2022,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [11]:
team_subset1 = df2[df2["Team2"] == 'Royal Challengers Bangalore'] 
team_subset2 = df2[df2["Team1"] == 'Royal Challengers Bangalore'] 

match_id_list_1 = team_subset1["ID"].to_numpy()
match_id_list_2 = team_subset2["ID"].to_numpy()

match_id_list = np.concatenate([match_id_list_1,match_id_list_2])
print(match_id_list)

[1304113 1304106 1304085 1304068 1304064 1304059 1304052 1254101 1254095
 1254103 1254083 1254076 1254073 1254058 1216494 1216522 1216519 1216514
 1216510 1178429 1178421 1178403 1175366 1175362 1136613 1136608 1136605
 1136599 1136579 1136574 1136571 1136568 1082646 1082628 1082624 1082617
 1082610 1082598 1082591  981013  981011  980995  980977  980953  980937
  980931  980927  829821  829807  829803  829795  829779  829757  829749
  829713  734027  734021  734013  733983  729313  729305  729281  598057
  598054  598064  598042  598036  598033  598012  598004  548376  548372
  548362  548360  548344  548336  548331  548318  501271  501260  501252
  501227  501222  501211  501208  501200  419154  419151  419140  419136
  419133  419119  419109  336002  336029  336023  336016  336010  335998
  335985 1312199 1312198 1304100 1304095 1304089 1304082 1304077 1304073
 1304049 1254115 1254090 1254108 1254113 1254087 1254079 1254067 1254063
 1237178 1216505 1216502 1216499 1216544 1216531 1216540 1216525 1216547
 1216534 1178424 1178417 1178414 1178410 1178406 1178395 1175372 1175369
 1175356 1136611 1136595 1136591 1136589 1136584 1136563 1082636 1082633
 1082621 1082607 1082602 1082595  981019  980999  980987  980981  980969
  980959  980921  980907  829819  829813  829785  829771  829763  829745
  829737  829719  734035  734005  733999  733991  733977  729299  729287
  598068  598045  598027  598023  598017  598008  598048  597999  548367
  548356  548350  548327  548324  548315  548310  501270  501268  501266
  501255  501247  501244  501232  501205  419164  419162  419157  419148
  419145  419128  419123  419115  419112  392239  392238  392236  392232
  392224  392221  392218  392213  392208  392204  392199  392194  392191
  392188  392185  392182  336012  336026  336006  336034  335996  335992
  335982]

In [13]:
m = len(match_id_list)

In [24]:
player_subset = player_subset[player_subset['BattingTeam']!='Royal Challengers Bangalore']

In [25]:
final_df = []
for i in range(len(player_subset)):
    if player_subset.iat[i,0] in match_id_list:
        final_df.append(player_subset.iloc[i])

In [26]:
final_df

[ID                        1254090
 innings                         2
 overs                          15
 ballnumber                      5
 batter                    SN Khan
 bowler                  YS Chahal
 non-striker            AK Markram
 extra_type                    NaN
 batsman_run                     0
 extras_run                      0
 total_run                       0
 non_boundary                    0
 isWicketDelivery                1
 player_out                SN Khan
 kind                       bowled
 fielders_involved             NaN
 BattingTeam          Punjab Kings
 Name: 24595, dtype: object,
 ID                           1178403
 innings                            1
 overs                              8
 ballnumber                         6
 batter                       SN Khan
 bowler                     YS Chahal
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        0
 extras_run                         0
 total_run                          0
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54466, dtype: object,
 ID                           1178403
 innings                            1
 overs                              9
 ballnumber                         6
 batter                       SN Khan
 bowler                        MM Ali
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        1
 extras_run                         0
 total_run                          1
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54472, dtype: object,
 ID                           1178403
 innings                            1
 overs                             10
 ballnumber                         5
 batter                       SN Khan
 bowler                     YS Chahal
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        4
 extras_run                         0
 total_run                          4
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54478, dtype: object,
 ID                           1178403
 innings                            1
 overs                             10
 ballnumber                         6
 batter                       SN Khan
 bowler                     YS Chahal
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        1
 extras_run                         0
 total_run                          1
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54479, dtype: object,
 ID                           1178403
 innings                            1
 overs                             11
 ballnumber                         1
 batter                       SN Khan
 bowler                        MM Ali
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        0
 extras_run                         0
 total_run                          0
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54481, dtype: object,
 ID                           1178403
 innings                            1
 overs                             11
 ballnumber                         2
 batter                       SN Khan
 bowler                        MM Ali
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        0
 extras_run                         0
 total_run                          0
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54482, dtype: object,
 ID                           1178403
 innings                            1
 overs                             11
 ballnumber                         3
 batter                       SN Khan
 bowler                        MM Ali
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        0
 extras_run                         0
 total_run                          0
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54483, dtype: object,
 ID                           1178403
 innings                            1
 overs                             11
 ballnumber                         4
 batter                       SN Khan
 bowler                        MM Ali
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        1
 extras_run                         0
 total_run                          1
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54484, dtype: object,
 ID                           1178403
 innings                            1
 overs                             11
 ballnumber                         6
 batter                       SN Khan
 bowler                        MM Ali
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        1
 extras_run                         0
 total_run                          1
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54486, dtype: object,
 ID                           1178403
 innings                            1
 overs                             12
 ballnumber                         1
 batter                       SN Khan
 bowler                Mohammed Siraj
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        1
 extras_run                         0
 total_run                          1
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54487, dtype: object,
 ID                           1178403
 innings                            1
 overs                             12
 ballnumber                         4
 batter                       SN Khan
 bowler                Mohammed Siraj
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        0
 extras_run                         0
 total_run                          0
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54490, dtype: object,
 ID                           1178403
 innings                            1
 overs                             12
 ballnumber                         5
 batter                       SN Khan
 bowler                Mohammed Siraj
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        6
 extras_run                         0
 total_run                          6
 non_boundary                       0
 isWicketDelivery                   0
 player_out                       NaN
 kind                             NaN
 fielders_involved                NaN
 BattingTeam          Kings XI Punjab
 Name: 54491, dtype: object,
 ID                           1178403
 innings                            1
 overs                             12
 ballnumber                         6
 batter                       SN Khan
 bowler                Mohammed Siraj
 non-striker                 CH Gayle
 extra_type                       NaN
 batsman_run                        0
 extras_run                         0
 total_run                          0
 non_boundary                       0
 isWicketDelivery                   1
 player_out                   SN Khan
 kind                          caught
 fielders_involved           PA Patel
 BattingTeam          Kings XI Punjab
 Name: 54492, dtype: object]

In [27]:
final_df = pd.DataFrame(final_df)

In [28]:
final_df

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
24595,1254090,2,15,5,SN Khan,YS Chahal,AK Markram,NaN,0,0,0,0,1,SN Khan,bowled,NaN,Punjab Kings
54466,1178403,1,8,6,SN Khan,YS Chahal,CH Gayle,NaN,0,0,0,0,0,NaN,NaN,NaN,Kings XI Punjab
54472,1178403,1,9,6,SN Khan,MM Ali,CH Gayle,NaN,1,0,1,0,0,NaN,NaN,NaN,Kings XI Punjab
54478,1178403,1,10,5,SN Khan,YS Chahal,CH Gayle,NaN,4,0,4,0,0,NaN,NaN,NaN,Kings XI Punjab
54479,1178403,1,10,6,SN Khan,YS Chahal,CH Gayle,NaN,1,0,1,0,0,NaN,NaN,NaN,Kings XI Punjab
54481,1178403,1,11,1,SN Khan,MM Ali,CH Gayle,NaN,0,0,0,0,0,NaN,NaN,NaN,Kings XI Punjab
54482,1178403,1,11,2,SN Khan,MM Ali,CH Gayle,NaN,0,0,0,0,0,NaN,NaN,NaN,Kings XI Punjab
54483,1178403,1,11,3,SN Khan,MM Ali,CH Gayle,NaN,0,0,0,0,0,NaN,NaN,NaN,Kings XI Punjab
54484,1178403,1,11,4,SN Khan,MM Ali,CH Gayle,NaN,1,0,1,0,0,NaN,NaN,NaN,Kings XI Punjab
54486,1178403,1,11,6,SN Khan,MM Ali,CH Gayle,NaN,1,0,1,0,0,NaN,NaN,NaN,Kings XI Punjab
54487,1178403,1,12,1,SN Khan,Mohammed Siraj,CH Gayle,NaN,1,0,1,0,0,NaN,NaN,NaN,Kings XI Punjab
54490,1178403,1,12,4,SN Khan,Mohammed Siraj,CH Gayle,NaN,0,0,0,0,0,NaN,NaN,NaN,Kings XI Punjab
54491,1178403,1,12,5,SN Khan,Mohammed Siraj,CH Gayle,NaN,6,0,6,0,0,NaN,NaN,NaN,Kings XI Punjab
54492,1178403,1,12,6,SN Khan,Mohammed Siraj,CH Gayle,NaN,0,0,0,0,1,SN Khan,caught,PA Patel,Kings XI Punjab

In [29]:
#Overall
if len(final_df)!=0:
    
    total_runs = final_df["batsman_run"].sum()
    print(total_runs)

    total_innings = len(pd.unique(final_df['ID']))
    print(total_innings)

    total_outs = final_df[final_df["player_out"] == 'DA Warner']
    print(len(total_outs))

    if len(total_outs)==0:
        print("Player not yet dismissed at ground")
    
    else:
        average = total_runs / len(total_outs)
        print(average)

    strike_rate = total_runs / len(final_df) * 100
    print(strike_rate)

    dots = final_df[final_df["batsman_run"] == 0]
    dot_percentage = len(dots)/len(final_df) * 100
    print(dot_percentage)

    boundaries = final_df[final_df["batsman_run"] == 4]
    sixes =  final_df[final_df["batsman_run"] == 6]
    boundary_percentage = len(boundaries) + len(sixes) / len(final_df) * 100
    print(boundary_percentage)

else:
    print("Player not played at ground")

15
2
0
Player not yet dismissed at ground
107.14285714285714
50.0
8.142857142857142

In [30]:
#1st_innings
if len(final_df)==0:
    print("Player not played in ground")
    
else:
    final_df_1 = final_df[final_df["innings"]==1]

    if len(final_df_1)!=0:

        total_runs = final_df_1["batsman_run"].sum()
        print(total_runs)

        total_innings = len(pd.unique(final_df_1['ID']))
        print(total_innings)

        total_outs = final_df_1[final_df_1["player_out"] == 'DA Warner']
        print(len(total_outs))

        if len(total_outs)==0:
            print("Player not yet dismissed at ground in 1st innings")

        else:
            average = total_runs / len(total_outs)
            print(average)

        strike_rate = total_runs / len(final_df_1) * 100
        print(strike_rate)

        dots = final_df_1[final_df_1["batsman_run"] == 0]
        dot_percentage = len(dots)/len(final_df_1) * 100
        print(dot_percentage)

        boundaries = final_df_1[final_df_1["batsman_run"] == 4]
        sixes =  final_df_1[final_df_1["batsman_run"] == 6]
        boundary_percentage = len(boundaries) + len(sixes) / len(final_df_1) * 100
        print(boundary_percentage)
    else:
            print("Player not played at ground in 1st innings")

15
1
0
Player not yet dismissed at ground
115.38461538461537
46.15384615384615
8.692307692307693

In [31]:
#2nd_innings
if len(final_df)==0:
    print("Player not played in ground")
    
else:
    final_df_2 = final_df[final_df["innings"]==2]
    
    if len(final_df_2)!=0:
        total_runs = final_df_2["batsman_run"].sum()
        print(total_runs)

        total_innings = len(pd.unique(final_df_2['ID']))
        print(total_innings)

        total_outs = final_df_2[final_df_2["player_out"] == 'DA Warner']
        print(len(total_outs))

        if len(total_outs)==0:
                print("Player not yet dismissed at ground in 2nd innings")

        else:
            average = total_runs / len(total_outs)
            print(average)

        strike_rate = total_runs / len(final_df_2) * 100
        print(strike_rate)

        dots = final_df_2[final_df_2["batsman_run"] == 0]
        dot_percentage = len(dots)/len(final_df_2) * 100
        print(dot_percentage)

        boundaries = final_df_2[final_df_2["batsman_run"] == 4]
        sixes =  final_df_2[final_df_2["batsman_run"] == 6]
        boundary_percentage = len(boundaries) + len(sixes) / len(final_df_2) * 100
        print(boundary_percentage)
        
    else:
            print("Player not played at ground in 2nd innings")

0
1
0
Player not yet dismissed at ground
0.0
100.0
0.0