In [1]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np 
import os
import pandas as pd

In [2]:
df = pd.read_csv('archive/IPL_Matches_2008_2022.csv')
df.dataframeName = 'matches.csv'

In [3]:
season_subset = df[(df["Season"] == 2022 )]
season_subset

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,29-05-2022,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,27-05-2022,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,25-05-2022,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,24-05-2022,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,22-05-2022,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,1304051,Pune,29-03-2022,2022,5,Rajasthan Royals,Sunrisers Hyderabad,"Maharashtra Cricket Association Stadium, Pune",Sunrisers Hyderabad,field,N,Rajasthan Royals,Runs,61.0,NaN,SV Samson,"['JC Buttler', 'YBK Jaiswal', 'SV Samson', 'D ...","['KS Williamson', 'Abhishek Sharma', 'RA Tripa...",BNJ Oxenford,UV Gandhe
70,1304050,Mumbai,28-03-2022,2022,4,Lucknow Super Giants,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Mohammed Shami,"['KL Rahul', 'Q de Kock', 'E Lewis', 'MK Pande...","['Shubman Gill', 'MS Wade', 'V Shankar', 'HH P...",PG Pathak,VK Sharma
71,1304049,Mumbai,27-03-2022,2022,3,Royal Challengers Bangalore,Punjab Kings,"Dr DY Patil Sports Academy, Mumbai",Punjab Kings,field,N,Punjab Kings,Wickets,5.0,NaN,OF Smith,"['F du Plessis', 'Anuj Rawat', 'V Kohli', 'KD ...","['MA Agarwal', 'S Dhawan', 'PBB Rajapaksa', 'L...",Nitin Menon,YC Barde
72,1304048,Mumbai,27-03-2022,2022,2,Mumbai Indians,Delhi Capitals,"Brabourne Stadium, Mumbai",Delhi Capitals,field,N,Delhi Capitals,Wickets,4.0,NaN,Kuldeep Yadav,"['RG Sharma', 'Ishan Kishan', 'Anmolpreet Sing...","['PP Shaw', 'TL Seifert', 'Mandeep Singh', 'RR...",RJ Tucker,HAS Khalid
73,1304047,Mumbai,26-03-2022,2022,1,Chennai Super Kings,Kolkata Knight Riders,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,6.0,NaN,UT Yadav,"['RD Gaikwad', 'DP Conway', 'RV Uthappa', 'AT ...","['AM Rahane', 'VR Iyer', 'N Rana', 'SS Iyer', ...",AK Chaudhary,Nitin Menon

In [118]:
team_subset1 = season_subset[season_subset["Team2"] == 'Chennai Super Kings'] 
team_subset2 = season_subset[season_subset["Team1"] == 'Chennai Super Kings'] 

match_id_list_1 = team_subset1["ID"].to_numpy()
match_id_list_2 = team_subset2["ID"].to_numpy()

match_id_list = np.concatenate([match_id_list_1,match_id_list_2])
print(match_id_list)

[1304095 1304084 1304079 1304057 1304114 1304108 1304105 1304101 1304092
 1304075 1304068 1304063 1304053 1304047]

In [119]:
df1 = pd.read_csv('archive/IPL_Ball_by_Ball_2008_2022.csv')
df1.dataframeName = 'deliveries.csv'
df1

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [120]:
final_df = []
for i in range(len(df1)):
    if df1.iat[i,0] in match_id_list:
        final_df.append(df1.iloc[i])

In [121]:
final_df = pd.DataFrame(final_df)
final_df = final_df[final_df["BattingTeam"]!="Chennai Super Kings"]
final_df

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
1569,1304114,2,0,1,YBK Jaiswal,Mukesh Choudhary,JC Buttler,NaN,4,0,4,0,0,NaN,NaN,NaN,Rajasthan Royals
1570,1304114,2,0,2,YBK Jaiswal,Mukesh Choudhary,JC Buttler,NaN,4,0,4,0,0,NaN,NaN,NaN,Rajasthan Royals
1571,1304114,2,0,3,YBK Jaiswal,Mukesh Choudhary,JC Buttler,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
1572,1304114,2,0,4,JC Buttler,Mukesh Choudhary,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1573,1304114,2,0,5,JC Buttler,Mukesh Choudhary,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17907,1304047,2,17,5,SS Iyer,DJ Bravo,SP Jackson,NaN,1,0,1,0,0,NaN,NaN,NaN,Kolkata Knight Riders
17908,1304047,2,17,6,SP Jackson,DJ Bravo,SS Iyer,NaN,1,0,1,0,0,NaN,NaN,NaN,Kolkata Knight Riders
17909,1304047,2,18,1,SP Jackson,AF Milne,SS Iyer,NaN,1,0,1,0,0,NaN,NaN,NaN,Kolkata Knight Riders
17910,1304047,2,18,2,SS Iyer,AF Milne,SP Jackson,NaN,2,0,2,0,0,NaN,NaN,NaN,Kolkata Knight Riders
17911,1304047,2,18,3,SS Iyer,AF Milne,SP Jackson,NaN,4,0,4,0,0,NaN,NaN,NaN,Kolkata Knight Riders

In [122]:
n = len(pd.unique(final_df['bowler']))

In [123]:
n

14

In [124]:
bowler_list = final_df["bowler"].unique()

In [125]:
for i in bowler_list:
    print(i)

Mukesh Choudhary
Simarjeet Singh
MJ Santner
M Pathirana
MM Ali
PH Solanki
DJ Bravo
M Theekshana
RA Jadeja
D Pretorius
CJ Jordan
TU Deshpande
S Dube
AF Milne